@startuml
title Pet
participant Client
participant APIGateway_Lambda
participant CreatePet
participant PetDao
database DynamoDB

Client -> APIGateway_Lambda : HTTP RQ
APIGateway_Lambda -> CreatePet : CreatePet Request

CreatePet-> DynamoDB : getPetId
DynamoDB --> CreatePet : return pet object
CreatePet --> APIGateway_Lambda : return CreatePetRequest
APIGateway_Lambda --> Client : return 2XX response with CreateEventResponse data

@enduml
